// Copyright (c) 2026 InfiniBand SR-IOV CNI Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"encoding/base64"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Multus pattern: the DaemonSet entrypoint generates a node-local kubeconfig
// from its own service account so the host-invoked CNI binary can reach the
// apiserver with the DaemonSet's identity (pods get/patch for the
// connection-details annotation). Regenerated periodically because bound
// service account tokens rotate.

// serviceAccountDir is the in-pod service-account secret mount. A var, not a
// const, so tests can redirect it to a temp dir.
var serviceAccountDir = "/var/run/secrets/kubernetes.io/serviceaccount"

const (
	kubeconfigFileName = "ib-sriov-cni.kubeconfig"
	kubeconfigSubDir   = "ib-sriov-cni.d"
	kubeconfigFileMode = 0o600
	kubeconfigDirMode  = 0o750
	// kubeconfigRefreshInterval keeps the host kubeconfig ahead of bound
	// service account token rotation.
	kubeconfigRefreshInterval = 10 * time.Minute
	kubeconfigTemplateNoCert  = `# Generated by ib-sriov-cni thin_entrypoint. Do not edit.
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: %s
    certificate-authority-data: %s
users:
- name: ib-sriov-cni
  user:
    token: "%s"
contexts:
- name: ib-sriov-cni-context
  context:
    cluster: local
    user: ib-sriov-cni
current-context: ib-sriov-cni-context
`
)

// apiServerURL builds the in-cluster apiserver URL. IPv6 hosts are bracketed;
// IPv4/hostnames are not (client-go rejects bracketed IPv4).
func apiServerURL() (string, error) {
	host := os.Getenv("KUBERNETES_SERVICE_HOST")
	port := os.Getenv("KUBERNETES_SERVICE_PORT")
	if host == "" || port == "" {
		return "", fmt.Errorf("KUBERNETES_SERVICE_HOST/PORT not set (not running in a pod?)")
	}
	if ip := net.ParseIP(host); ip != nil && ip.To4() == nil && strings.Contains(host, ":") {
		host = "[" + host + "]"
	}
	return "https://" + host + ":" + port, nil
}

// generateKubeconfig writes the kubeconfig under cniConfDir (host mount of
// /etc/cni/net.d) using this pod's service account token + CA.
func generateKubeconfig(cniConfDir string) error {
	token, err := os.ReadFile(filepath.Join(serviceAccountDir, "token"))
	if err != nil {
		return fmt.Errorf("failed to read service account token: %v", err)
	}
	ca, err := os.ReadFile(filepath.Join(serviceAccountDir, "ca.crt"))
	if err != nil {
		return fmt.Errorf("failed to read service account CA: %v", err)
	}
	server, err := apiServerURL()
	if err != nil {
		return err
	}

	// cniConfDir is the host's /etc/cni/net.d bind-mount. If it is absent the
	// hostPath volume was not mounted; MkdirAll would then silently create a
	// container-local directory and the host-invoked CNI would never find the
	// kubeconfig while the DaemonSet still reports success. Fail loudly instead
	// of creating the parent chain.
	if info, statErr := os.Stat(cniConfDir); statErr != nil || !info.IsDir() {
		return fmt.Errorf("CNI conf dir %s not present (is the /etc/cni/net.d hostPath mounted?): %v",
			cniConfDir, statErr)
	}
	dir := filepath.Join(cniConfDir, kubeconfigSubDir)
	if err := os.MkdirAll(dir, kubeconfigDirMode); err != nil {
		return fmt.Errorf("failed to create %s: %v", dir, err)
	}

	content := fmt.Sprintf(kubeconfigTemplateNoCert,
		server,
		base64.StdEncoding.EncodeToString(ca),
		strings.TrimSpace(string(token)))

	dst := filepath.Join(dir, kubeconfigFileName)
	tmp := dst + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), kubeconfigFileMode); err != nil {
		return fmt.Errorf("failed to write %s: %v", tmp, err)
	}
	if err := os.Rename(tmp, dst); err != nil {
		_ = os.Remove(tmp) // don't leave the token-bearing temp file on the host
		return fmt.Errorf("failed to move kubeconfig into place: %v", err)
	}
	fmt.Printf("Generated kubeconfig at %q (server %s)\n", dst, server)
	return nil
}
