---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-infiniband-cni-ds-amd64
  namespace: kube-system
  labels:
    tier: node
    app: infiniband-cni
spec:
  template:
    metadata:
      labels:
        tier: node
        app: infiniband-cni
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: kube-infiniband-cni
          image: mellanox/infiniband-cni
          imagePullPolicy: Never
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
          volumeMounts:
            - name: cnibin
              mountPath: /host/opt/cni/bin
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-infiniband-cni-ds-ppc64le
  namespace: kube-system
  labels:
    tier: node
    app: infiniband-cni
spec:
  template:
    metadata:
      labels:
        tier: node
        app: infiniband-cni
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: ppc64le
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: kube-infiniband-cni
          image: mellanox/infiniband-cni:ppc64le
          imagePullPolicy: Never
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
          volumeMounts:
            - name: cnibin
              mountPath: /host/opt/cni/bin
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin